spring.application.name=Employee-Full-CURD-REST-API

#Database configuration Info
spring.datasource.url =${DB_URL}
spring.datasource.username =${DB_USERNAME}
spring.datasource.password =${DB_PASSWORD}
